apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: asyncapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    asyncapi: 2.4.0
    info:
      title: API Document for Confluent Cluster
      version: 1.0.0
    servers:
      cluster:
        url: https://pkc-nk1pv.europe-west3.gcp.confluent.cloud:443
        description: Confluent Kafka instance.
        protocol: kafka
        security:
        - confluentBroker: []
      schema-registry:
        url: https://psrc-lgkvv.europe-west3.gcp.confluent.cloud
        description: Confluent Kafka Schema Registry Server
        protocol: kafka
        security:
        - confluentSchemaRegistry: []
    channels:
      KsqlDbAvroSpec-topic:
        subscribe:
          operationId: KsqlDbAvroSpecTopicSubscribe
          bindings:
            kafka:
              bindingVersion: 0.3.0
              groupId:
                type: string
              clientId:
                type: string
          message:
            $ref: '#/components/messages/KsqlDbAvroSpecTopicMessage'
        bindings:
          kafka:
            x-configs:
              cleanup.policy: delete
              delete.retention.ms: 8.64e+07
              confluent.value.schema.validation: "true"
        x-messageCompatibility: BACKWARD
      pageviews:
        subscribe:
          tags:
          - name: containsprivacy
          operationId: PageviewsSubscribe
          bindings:
            kafka:
              bindingVersion: 0.3.0
              groupId:
                type: string
              clientId:
                type: string
          message:
            $ref: '#/components/messages/PageviewsMessage'
        bindings:
          kafka:
            x-configs:
              cleanup.policy: delete
              delete.retention.ms: 8.64e+07
              confluent.value.schema.validation: "true"
        x-messageCompatibility: BACKWARD
    components:
      messages:
        KsqlDbAvroSpecTopicMessage:
          schemaFormat: application/vnd.apache.avro;version=1.9.0
          contentType: application/avro
          payload:
            connect.name: io.confluent.ksql.avro_schemas.KsqlDataSourceSchema
            fields:
            - default: null
              name: AMOUNT
              type:
              - "null"
              - int
            name: KsqlDataSourceSchema
            namespace: io.confluent.ksql.avro_schemas
            type: record
          name: KsqlDbAvroSpecTopicMessage
          bindings:
            kafka:
              bindingVersion: 0.3.0
              key:
                type: string
        PageviewsMessage:
          schemaFormat: application/vnd.apache.avro;version=1.9.0
          contentType: application/avro
          payload:
            doc: Sample schema to help you get started.
            fields:
            - doc: The int type is a 32-bit signed integer.
              name: my_field1
              type: int
            - doc: The double type is a double precision (64-bit) IEEE 754 floating-point
                number.
              name: my_field2
              type: double
            - doc: The string is a unicode character sequence.
              name: my_field3
              type: string
            name: sampleRecord
            namespace: com.mycorp.mynamespace
            type: record
          tags:
          - name: containsprivacy
          name: PageviewsMessage
          bindings:
            kafka:
              bindingVersion: 0.3.0
              key:
                type: string
      securitySchemes:
        confluentBroker:
          type: userPassword
          x-configs:
            sasl.mechanisms: PLAIN
            sasl.password: '{{CLUSTER_API_SECRET}}'
            sasl.username: '{{CLUSTER_API_KEY}}'
            security.protocol: sasl_ssl
        confluentSchemaRegistry:
          type: userPassword
          x-configs:
            basic.auth.user.info: '{{SCHEMA_REGISTRY_API_KEY}}:{{SCHEMA_REGISTRY_API_SECRET}}'  
      



